### ISSUE TITLE
Viewer cannot open all CSV output

### ISSUE THREAD

**Issue by leomaury** [bioimageit/bioimageit#27]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by KevinFournier** [comment]
@leomaury Do you have more context for this error ? What CSV cannot be open ? Is it after a specific process ? Do you have example that reproduce the error ?

**Comment by leomaury** [comment]
@KevinFournier 
First, you need to use cellpose (in segmentation, make sure it is up to date, I did a bug fix last week) to generate a mask image (use cellpose on the segmentation.tif in images_test, don't worry for the parameters)
Then, you use LabelsMeasure (in measure), on the segmentation.tif and the mask you generated before.
The output will be a CSV, it should be generated without problems but the display of it within BioImageIT UI could not work

**Comment by KevinFournier** [comment]
corrected with commit https://github.com/bioimageit/bioimageit_core/commit/de4c460147ba399fff5bf15ddd346bbd034a34e3
