### ISSUE TITLE
Cannot view images in the experiment page

### ISSUE THREAD

**Issue by leomaury** [bioimageit/bioimageit#37]
ERROR when we click on "view" : 
![image](https://user-images.githubusercontent.com/42140279/228491316-73b12ec3-a1d2-4db6-b4bb-0251c259f882.png)
![image](https://user-images.githubusercontent.com/42140279/228491372-0faa069f-8511-4c02-a5f2-81faebe5dba0.png)

**Comment by KevinFournier** [comment]
Fixed in commit https://github.com/bioimageit/bioimageit_viewer/commit/6971cdfc98ce9b2ae35259ede006dcce8dd87a92 on main
